const express = require('express');
const path = require('path');
const app = express();
const port = process.env.PORT || 3000;
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(express.static(path.join(__dirname, 'public')));
app.get('/api/health', (req, res) => { res.json({ status: 'ok', app: 'Ordeminds', uptime: process.uptime() }); });
app.get('/login', (req, res) => res.sendFile(path.join(__dirname, 'public', 'login.html')));
app.post('/login', (req, res) => { console.log('Login attempt:', req.body?.email); res.redirect('/app.html'); });
app.listen(port, () => { console.log(`Ordeminds listening on port ${port}`); });
